'use strict';

/* AtlasIQ — browser-native decision intelligence
   Built with zero external runtime dependencies for GitHub Pages. */

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const clamp = (n,min,max) => Math.min(max,Math.max(min,n));
const avg = a => a.length ? a.reduce((s,v)=>s+v,0)/a.length : 0;
const sum = a => a.reduce((s,v)=>s+v,0);
const round = (n,d=1) => Number.isFinite(n) ? +n.toFixed(d) : 0;
const escapeHTML = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function getActiveProfileRecord(){try{const id=localStorage.getItem('atlasiq_active_profile');const profiles=JSON.parse(localStorage.getItem('atlasiq_profiles')||'[]');return profiles.find(p=>p.id===id)||null}catch{return null}}
function currentUniversity(){return getActiveProfileRecord()?.university||'Purdue University'}
function scopedStorageKey(k){if(['atlasiq_theme','atlasiq_profiles','atlasiq_active_profile','atlasiq_guest_mode'].includes(k))return k;const id=localStorage.getItem('atlasiq_active_profile')||'guest';return `atlasiq_profile_${id}_${k.replace(/^atlasiq_/, '')}`}
const storage = {get:(k,f)=>{try{return JSON.parse(localStorage.getItem(scopedStorageKey(k)))??f}catch{return f}},set:(k,v)=>{try{localStorage.setItem(scopedStorageKey(k),JSON.stringify(v))}catch{}},remove:(k)=>{try{localStorage.removeItem(scopedStorageKey(k))}catch{}},key:scopedStorageKey};
let toastTimer;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast('Copied to clipboard')).catch(()=>toast('Copy failed'))}
function downloadFile(name, content, type='application/json'){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function formatNumber(n){if(!Number.isFinite(n)) return '—';if(Math.abs(n)>=1e6)return (n/1e6).toFixed(1)+'M';if(Math.abs(n)>=1e3)return (n/1e3).toFixed(1)+'K';return Math.abs(n)%1===0?String(n):n.toFixed(2)}

// ---------- Global motion, navigation, command palette ----------
const root=document.documentElement;
const savedTheme=storage.get('atlasiq_theme','dark');
if(savedTheme==='light')root.classList.add('light');
$('#themeBtn').addEventListener('click',()=>{root.classList.toggle('light');storage.set('atlasiq_theme',root.classList.contains('light')?'light':'dark');drawAllCanvases();});

const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});
$$('.reveal').forEach(el=>revealObserver.observe(el));

const counters=$$('[data-counter]');
const counterObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=+el.dataset.counter,start=performance.now();const tick=t=>{const p=Math.min(1,(t-start)/1100);el.textContent=Math.round(target*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);counterObs.unobserve(el)}));
counters.forEach(e=>counterObs.observe(e));

const tilt=$('.tilt-card');
if(tilt){tilt.addEventListener('pointermove',e=>{const r=tilt.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;tilt.style.transform=`rotateY(${x*7}deg) rotateX(${-y*7}deg)`});tilt.addEventListener('pointerleave',()=>tilt.style.transform='');}

// particles
const particleCanvas=$('#particleCanvas'),pctx=particleCanvas.getContext('2d');
let particles=[];
function resizeParticles(){const dpr=Math.min(2,devicePixelRatio||1);particleCanvas.width=innerWidth*dpr;particleCanvas.height=innerHeight*dpr;particleCanvas.style.width=innerWidth+'px';particleCanvas.style.height=innerHeight+'px';pctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:Math.min(90,Math.floor(innerWidth/16))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18,r:Math.random()*1.5+.4}))}
function animateParticles(){pctx.clearRect(0,0,innerWidth,innerHeight);const light=root.classList.contains('light');for(const p of particles){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;pctx.fillStyle=light?'rgba(40,50,75,.28)':'rgba(245,207,98,.55)';pctx.beginPath();pctx.arc(p.x,p.y,p.r,0,Math.PI*2);pctx.fill()}for(let i=0;i<particles.length;i++)for(let j=i+1;j<particles.length;j++){const a=particles[i],b=particles[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<105){pctx.strokeStyle=light?`rgba(40,50,75,${.06*(1-d/105)})`:`rgba(245,207,98,${.11*(1-d/105)})`;pctx.beginPath();pctx.moveTo(a.x,a.y);pctx.lineTo(b.x,b.y);pctx.stroke()}}requestAnimationFrame(animateParticles)}
resizeParticles();animateParticles();addEventListener('resize',resizeParticles);

const commandItems=[
  ['Command Center','#campus','Campus dashboard'],['Semester Simulator','#campus','Model your workload'],['Ripple Engine','#campus','Trace decision consequences'],['Career Intelligence','#campus','Analyze internship readiness'],['Campus Navigator','#campus','Evaluate class transitions'],['Data Studio','#studio','Upload and profile a CSV'],['AutoML Arena','#studio','Compare local models'],['Decision Simulator','#studio','Run what-if analysis'],['AtlasIQ Analyst','#studio','Ask questions about data'],['ProofGraph','#proofgraph','Inspect skill evidence'],['Founder','#about','Meet Niveditha']
];
const palette=$('#commandPalette'),commandInput=$('#commandInput'),commandResults=$('#commandResults');
function renderCommands(q=''){const filtered=commandItems.filter(x=>x.join(' ').toLowerCase().includes(q.toLowerCase()));commandResults.innerHTML=filtered.map((x,i)=>`<button class="command-result ${i===0?'active':''}" data-command="${escapeHTML(x[0])}"><span>${escapeHTML(x[0])}</span><small>${escapeHTML(x[2])}</small></button>`).join('');$$('[data-command]',commandResults).forEach(b=>b.onclick=()=>runCommand(b.dataset.command))}
function openPalette(){palette.classList.add('open');palette.setAttribute('aria-hidden','false');renderCommands();setTimeout(()=>commandInput.focus(),20)}
function closePalette(){palette.classList.remove('open');palette.setAttribute('aria-hidden','true')}
function runCommand(name){const item=commandItems.find(x=>x[0]===name);if(!item)return;closePalette();document.querySelector(item[1]).scrollIntoView();if(name==='Semester Simulator')activateCampus('semester');if(name==='Ripple Engine')activateCampus('ripple');if(name==='Career Intelligence')activateCampus('career');if(name==='Campus Navigator')activateCampus('navigator');if(name==='AutoML Arena')activateStudio('automl');if(name==='Decision Simulator')activateStudio('simulate');if(name==='AtlasIQ Analyst')activateStudio('explain')}
$('#commandBtn').onclick=openPalette;commandInput.oninput=e=>renderCommands(e.target.value);palette.querySelector('.modal-backdrop').onclick=closePalette;addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape'){closePalette();closeMethodModal()}});

// draggable dashboard cards
let dragged=null;$$('.draggable').forEach(card=>{card.addEventListener('dragstart',()=>{dragged=card;card.style.opacity=.45});card.addEventListener('dragend',()=>{card.style.opacity='';dragged=null});card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',e=>{e.preventDefault();if(!dragged||dragged===card)return;const parent=card.parentElement;const children=[...parent.children];children.indexOf(dragged)<children.indexOf(card)?parent.insertBefore(dragged,card.nextSibling):parent.insertBefore(dragged,card);toast('Dashboard rearranged')})});

// ---------- Canvas helpers ----------
function setupCanvas(canvas){const rect=canvas.getBoundingClientRect();if(!rect.width)return null;const dpr=Math.min(2,devicePixelRatio||1),w=Math.round(rect.width*dpr),h=Math.round((canvas.getAttribute('height')/canvas.getAttribute('width'))*rect.width*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return {ctx,w:rect.width,h:h/dpr}}
function paletteColors(){return root.classList.contains('light')?{text:'#172033',muted:'#667085',line:'rgba(20,30,50,.12)',gold:'#b98717',cyan:'#1689a4',green:'#16875a',red:'#d33e59',purple:'#7254c9',panel:'#fff'}:{text:'#f5f7fb',muted:'#9ca6bc',line:'rgba(255,255,255,.10)',gold:'#f5cf62',cyan:'#66e5ff',green:'#67e8a3',red:'#ff7d8d',purple:'#ad8cff',panel:'#11172a'}}
function drawAxes(ctx,w,h,pad,c){ctx.strokeStyle=c.line;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad,h-pad);ctx.lineTo(w-pad,h-pad);ctx.moveTo(pad,pad);ctx.lineTo(pad,h-pad);ctx.stroke()}
function drawLineChart(canvas,values,{labels=[],color='gold',fill=true,min=null,max=null,highlight=-1}={}){const s=setupCanvas(canvas);if(!s||!values.length)return;const {ctx,w,h}=s,c=paletteColors(),pad=38;ctx.clearRect(0,0,w,h);const lo=min??Math.min(...values),hi=max??Math.max(...values),range=hi-lo||1;drawAxes(ctx,w,h,pad,c);ctx.font='11px sans-serif';ctx.fillStyle=c.muted;ctx.textAlign='right';for(let i=0;i<4;i++){const val=lo+range*(i/3),y=h-pad-(i/3)*(h-pad*2);ctx.fillText(round(val),pad-8,y+4);ctx.strokeStyle=c.line;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()}const pts=values.map((v,i)=>({x:pad+(i/(Math.max(1,values.length-1)))*(w-pad*2),y:h-pad-((v-lo)/range)*(h-pad*2)}));if(fill){const grad=ctx.createLinearGradient(0,pad,0,h-pad);grad.addColorStop(0,c[color]+'55');grad.addColorStop(1,c[color]+'00');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(pts[0].x,h-pad);pts.forEach(p=>ctx.lineTo(p.x,p.y));ctx.lineTo(pts.at(-1).x,h-pad);ctx.closePath();ctx.fill()}ctx.strokeStyle=c[color];ctx.lineWidth=2.2;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();pts.forEach((p,i)=>{ctx.fillStyle=i===highlight?c.red:c[color];ctx.beginPath();ctx.arc(p.x,p.y,i===highlight?5:2.5,0,Math.PI*2);ctx.fill();if(labels[i]&&(i%Math.ceil(values.length/7)===0||i===values.length-1)){ctx.fillStyle=c.muted;ctx.textAlign='center';ctx.fillText(labels[i],p.x,h-pad+18)}})}
function drawBarChart(canvas,labels,values,{color='gold',horizontal=false}={}){const s=setupCanvas(canvas);if(!s||!values.length)return;const {ctx,w,h}=s,c=paletteColors(),pad=44;ctx.clearRect(0,0,w,h);const max=Math.max(...values.map(Math.abs),1);ctx.font='10px sans-serif';if(horizontal){const bh=(h-pad*2)/values.length*.62;values.forEach((v,i)=>{const y=pad+i*(h-pad*2)/values.length;ctx.fillStyle=c.line;ctx.fillRect(130,y,w-pad-135,bh);ctx.fillStyle=c[color];ctx.fillRect(130,y,(w-pad-135)*Math.abs(v)/max,bh);ctx.fillStyle=c.muted;ctx.textAlign='right';ctx.fillText(String(labels[i]).slice(0,18),122,y+bh*.72);ctx.textAlign='left';ctx.fillText(round(v,2),135+(w-pad-135)*Math.abs(v)/max,y+bh*.72)})}else{drawAxes(ctx,w,h,pad,c);const bw=(w-pad*2)/values.length*.68;values.forEach((v,i)=>{const x=pad+i*(w-pad*2)/values.length+(w-pad*2)/values.length*.16,bh=(h-pad*2)*Math.abs(v)/max;ctx.fillStyle=c[color];ctx.fillRect(x,h-pad-bh,bw,bh);ctx.save();ctx.translate(x+bw/2,h-pad+14);ctx.rotate(-.35);ctx.fillStyle=c.muted;ctx.textAlign='right';ctx.fillText(String(labels[i]).slice(0,12),0,0);ctx.restore()})}}
function drawScatter(canvas,xs,ys,{xLabel='',yLabel='',line=false}={}){const s=setupCanvas(canvas);if(!s||!xs.length)return;const {ctx,w,h}=s,c=paletteColors(),pad=48;ctx.clearRect(0,0,w,h);const xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),xr=xmax-xmin||1,yr=ymax-ymin||1;drawAxes(ctx,w,h,pad,c);ctx.fillStyle=c.muted;ctx.font='10px sans-serif';ctx.textAlign='center';ctx.fillText(xLabel,w/2,h-7);ctx.save();ctx.translate(12,h/2);ctx.rotate(-Math.PI/2);ctx.fillText(yLabel,0,0);ctx.restore();const pts=xs.map((x,i)=>({x:pad+(x-xmin)/xr*(w-pad*2),y:h-pad-(ys[i]-ymin)/yr*(h-pad*2)}));if(line){ctx.strokeStyle=c.gold;ctx.lineWidth=1.5;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}ctx.fillStyle=c.cyan;pts.forEach(p=>{ctx.globalAlpha=.72;ctx.beginPath();ctx.arc(p.x,p.y,3.1,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1}
function drawAllCanvases(){drawWorkload();drawCampusMap();drawProofGraph();if(dataState.profile){renderCorrelation();renderMainChart();drawSimulationChart()}}

// ---------- Campus OS tabs ----------
function activateCampus(name){$$('.workspace-tab').forEach(b=>b.classList.toggle('active',b.dataset.campusTab===name));$$('.campus-panel').forEach(p=>p.classList.toggle('active',p.id===`campus-${name}`));if(name==='navigator')setTimeout(drawCampusMap,30);if(name==='ripple')setTimeout(runRipple,30)}
$$('.workspace-tab').forEach(b=>b.onclick=()=>activateCampus(b.dataset.campusTab));$$('[data-jump]').forEach(b=>b.onclick=()=>activateCampus(b.dataset.jump));
function activateStudio(name){$$('.studio-tab').forEach(b=>b.classList.toggle('active',b.dataset.studioTab===name));$$('.studio-panel').forEach(p=>p.classList.toggle('active',p.id===`studio-${name}`));if(name==='visuals'&&dataState.profile)setTimeout(()=>{renderMainChart();renderCorrelation()},30);if(name==='simulate'&&dataState.profile)setTimeout(drawSimulationChart,30)}
$$('.studio-tab').forEach(b=>b.onclick=()=>activateStudio(b.dataset.studioTab));

// ---------- Command center ----------
const workload=[28,31,34,37,43,39,46,51,58,49,45,42,48,37,32,27];
function drawWorkload(){drawLineChart($('#workloadChart'),workload,{labels:workload.map((_,i)=>`W${i+1}`),highlight:8,color:'gold'})}drawWorkload();

// ---------- Semester simulator ----------
const courseCatalog=[
  {id:'CS 182',name:'Foundations of Computer Science',credits:3,hours:10,difficulty:4.4,project:2,career:7},
  {id:'CS 240',name:'Programming in C',credits:3,hours:11,difficulty:4.5,project:4,career:9},
  {id:'MA 351',name:'Elementary Linear Algebra',credits:3,hours:8,difficulty:3.8,project:1,career:8},
  {id:'STAT 350',name:'Introduction to Statistics',credits:3,hours:8,difficulty:3.4,project:2,career:9},
  {id:'CS 38003',name:'Python Programming',credits:3,hours:7,difficulty:3.0,project:6,career:8},
  {id:'TDM 102',name:'The Data Mine Seminar II',credits:1,hours:4,difficulty:2.5,project:6,career:8},
  {id:'PHIL 110',name:'Introduction to Philosophy',credits:3,hours:6,difficulty:2.8,project:1,career:2},
  {id:'COM 114',name:'Fundamentals of Speech',credits:3,hours:5,difficulty:2.4,project:3,career:4},
  {id:'MGMT 200',name:'Introductory Accounting',credits:3,hours:7,difficulty:3.2,project:2,career:5},
  {id:'STAT 416',name:'Probability',credits:3,hours:10,difficulty:4.2,project:1,career:9},
  {id:'CS 373',name:'Data Mining & Machine Learning',credits:3,hours:12,difficulty:4.6,project:7,career:10},
  {id:'CS 307',name:'Software Engineering I',credits:3,hours:12,difficulty:4.1,project:10,career:10}
];
const savedCustomCourses=storage.get('atlasiq_custom_courses',[]);savedCustomCourses.forEach(c=>{if(c&&c.id&&!courseCatalog.some(x=>x.id===c.id))courseCatalog.push(c)});
const courseSelect=$('#courseSelect');courseSelect.innerHTML=courseCatalog.map((c,i)=>`<option value="${i}">${c.id} — ${c.name}</option>`).join('');
const starterCourseIds=(getActiveProfileRecord()?.university||'').toLowerCase().includes('purdue')?['CS 182','MA 351','TDM 102','PHIL 110']:[];
let selectedCourses=storage.get('atlasiq_courses',starterCourseIds).map(id=>courseCatalog.find(c=>c.id===id)).filter(Boolean);
function renderCourses(){storage.set('atlasiq_courses',selectedCourses.map(c=>c.id));$('#selectedCourses').innerHTML=selectedCourses.map(c=>`<div class="course-chip"><div><b>${c.id}</b><small>${c.name} · ${c.credits} cr · ~${c.hours} hrs/wk</small></div><button data-remove-course="${c.id}" aria-label="Remove ${c.id}">×</button></div>`).join('')||'<p class="muted">Add courses to model a semester.</p>';$$('[data-remove-course]').forEach(b=>b.onclick=()=>{selectedCourses=selectedCourses.filter(c=>c.id!==b.dataset.removeCourse);renderCourses();updateSemester()});}
$('#addCourseBtn').onclick=()=>{const c=courseCatalog[+courseSelect.value];if(selectedCourses.some(x=>x.id===c.id))return toast('Course already added');selectedCourses.push(c);renderCourses();updateSemester()};
const semesterInputs=['workHours','clubHours','sleepHours','commute'];semesterInputs.forEach(id=>$('#'+id).addEventListener('input',updateSemester));
function updateSemester(){const work=+$(`#workHours`).value,club=+$(`#clubHours`).value,sleep=+$(`#sleepHours`).value,commute=+$(`#commute`).value;$('#workHoursOut').textContent=work+'h';$('#clubHoursOut').textContent=club+'h';$('#sleepHoursOut').textContent=sleep+'h';$('#commuteOut').textContent=commute+'m';const credits=sum(selectedCourses.map(c=>c.credits)),study=sum(selectedCourses.map(c=>c.hours)),difficulty=avg(selectedCourses.map(c=>c.difficulty))||0,project=sum(selectedCourses.map(c=>c.project)),career=avg(selectedCourses.map(c=>c.career))||0,total=study+work+club+commute/60*5;const sleepScore=clamp(100-Math.abs(8-sleep)*18,30,100),loadScore=clamp(105-Math.max(0,total-38)*2.5-Math.max(0,credits-15)*3,25,100),difficultyScore=clamp(115-difficulty*12-Math.max(0,selectedCourses.filter(c=>c.difficulty>4).length-1)*10,30,100),careerScore=clamp(45+career*5+project*.45,30,100),timeScore=clamp(105-(work+club)-commute/3,25,100);const score=Math.round(loadScore*.30+difficultyScore*.19+sleepScore*.21+careerScore*.18+timeScore*.12);const risk=score>=83?'Low–moderate':score>=68?'Moderate':'High';const peak=total>52||difficulty>4.2;$('#semesterScore').textContent=score;$('#semesterRing').style.setProperty('--score',score);$('#semesterVerdict').textContent=score>=88?'Exceptionally balanced':score>=78?'Strong, with one pressure point':score>=65?'Ambitious and manageable with structure':'Overloaded—redesign recommended';$('#semesterSummary').textContent=peak?'Multiple high-intensity courses create a concentrated project and exam risk. Protect early start time.':'The modeled workload leaves enough recovery capacity while advancing technical and career goals.';$('#creditsPill').textContent=credits+' credits';$('#loadPill').textContent=Math.round(total)+' hrs/week';$('#riskPill').textContent=risk+' risk';const factors=[['Workload capacity',loadScore],['Difficulty mix',difficultyScore],['Sleep resilience',sleepScore],['Career value',careerScore],['Time flexibility',timeScore]];$('#factorBars').innerHTML=factors.map(([n,v])=>`<div class="factor-row"><span>${n}</span><i><b style="--value:${v}%"></b></i><em>${Math.round(v)}</em></div>`).join('');const hardest=[...selectedCourses].sort((a,b)=>b.difficulty-a.difficulty)[0];const explanation=`The score weights workload capacity (30%), sleep resilience (21%), course difficulty mix (19%), career value (18%), and flexible time (12%). ${hardest?hardest.id+' is the highest-intensity course in this plan. ':''}${total>45?`Your modeled commitment is ${Math.round(total)} hours per week, so the engine recommends beginning technical milestones early and preserving at least one low-load evening.`:`Your modeled commitment is ${Math.round(total)} hours per week, leaving a reasonable buffer for deadlines and unexpected work.`}`;$('#semesterExplain').textContent=explanation;$('#metricBalance').textContent=score;$('#metricHours').textContent=Math.round(total);$('#metricCareer').textContent=Math.round(careerScore*.8);}
$('#copySemesterExplain').onclick=()=>copyText($('#semesterExplain').textContent);$$('.scenario-save').forEach(b=>b.onclick=()=>{const slot=b.dataset.slot;const state={score:+$('#semesterScore').textContent,credits:sum(selectedCourses.map(c=>c.credits)),hours:+$('#metricHours').textContent,courses:selectedCourses.map(c=>c.id)};storage.set('atlasiq_scenario_'+slot,state);renderScenarios();toast(`Scenario ${slot} saved`) });
function renderScenarios(){$('#scenarioCompare').innerHTML=['A','B','C'].map(slot=>{const s=storage.get('atlasiq_scenario_'+slot,null);return s?`<div class="scenario-card"><span>SCENARIO ${slot}</span><strong>${s.score}</strong><small>${s.credits} credits · ${s.hours}h<br>${s.courses.join(', ')}</small></div>`:`<div class="scenario-card"><span>SCENARIO ${slot}</span><small>Not saved</small></div>`}).join('')}
renderCourses();updateSemester();renderScenarios();

// ---------- Ripple Engine ----------
const rippleDecision=$('#rippleDecision'),rippleMagnitude=$('#rippleMagnitude');
function rippleLabel(){const m=+rippleMagnitude.value,map={course:`${m} course${m>1?'s':''}`,job:`${m*4} hrs/week`,club:`${m} organization${m>1?'s':''}`,project:`${m} project milestone${m>1?'s':''}`,sleep:`${m*.5} hrs/night`};$('#rippleValueLabel').textContent=map[rippleDecision.value]}
rippleDecision.onchange=rippleLabel;rippleMagnitude.oninput=rippleLabel;
function runRipple(){const type=rippleDecision.value,m=+rippleMagnitude.value,priority=$('#ripplePriority').value;let d={workload:0,career:0,academic:0,time:0,resilience:0};if(type==='course')d={workload:-7*m,career:5*m,academic:-3*m,time:-6*m,resilience:-4*m};if(type==='job')d={workload:-5*m,career:2*m,academic:-2*m,time:-7*m,resilience:-3*m};if(type==='club')d={workload:-2*m,career:6*m,academic:0,time:-3*m,resilience:1*m};if(type==='project')d={workload:-3*m,career:9*m,academic:1*m,time:-4*m,resilience:3*m};if(type==='sleep')d={workload:2*m,career:1*m,academic:5*m,time:-2*m,resilience:8*m};if(priority==='career')d.career*=1.18;if(priority==='academic')d.academic*=1.25;if(priority==='time')d.time*=.7;if(priority==='balance')d.resilience*=1.12;Object.keys(d).forEach(k=>d[k]=round(d[k],1));const svg=$('#rippleGraph'),nodes=[['DECISION',380,65,0],['Workload',125,200,d.workload],['Career',300,305,d.career],['Academic',460,305,d.academic],['Free time',635,200,d.time],['Resilience',380,190,d.resilience]];const edges=[[0,1],[0,4],[0,5],[5,2],[5,3],[1,2],[4,3]];svg.innerHTML=`<defs><filter id="rGlow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>${edges.map(([a,b])=>`<line class="ripple-edge" x1="${nodes[a][1]}" y1="${nodes[a][2]}" x2="${nodes[b][1]}" y2="${nodes[b][2]}"/>`).join('')}${nodes.map((n,i)=>`<g class="ripple-node ${n[3]<0?'negative':''}" transform="translate(${n[1]} ${n[2]})"><circle r="${i?48:58}" filter="url(#rGlow)"/><text y="-5">${n[0]}</text><text class="delta" y="19">${i?(n[3]>0?'+':'')+n[3]+'%':'WHAT IF'}</text></g>`).join('')}`;const ups=Object.entries(d).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]),downs=Object.entries(d).filter(x=>x[1]<0).sort((a,b)=>a[1]-b[1]);const unc=Math.max(3,Math.round(m*2.5));$('#rippleNarrative').innerHTML=`<b>Modeled result:</b> The strongest upside is <b>${ups[0]?.[0]||'balance'} (${ups[0]?.[1]>0?'+':''}${ups[0]?.[1]||0}%)</b>, while the largest tradeoff is <b>${downs[0]?.[0]||'none'} (${downs[0]?.[1]||0}%)</b>. Expected uncertainty is approximately ±${unc} percentage points because outcomes depend on course timing, prior preparation, and execution quality.`}
$('#runRipple').onclick=runRipple;rippleLabel();runRipple();

// ---------- Career Intelligence ----------
const roleProfiles={
  'Data Science Intern':['python','sql','pandas','statistics','machine learning','scikit-learn','data visualization','git','jupyter','experimentation','communication','model deployment','docker','cloud'],
  'Data Analyst Intern':['sql','excel','python','pandas','statistics','tableau','power bi','data visualization','data cleaning','communication','business analysis','git'],
  'Machine Learning Intern':['python','machine learning','scikit-learn','pytorch','tensorflow','statistics','linear algebra','git','docker','cloud','model deployment','algorithms'],
  'Data Engineering Intern':['python','sql','data pipelines','spark','airflow','cloud','docker','git','databases','etl','data modeling','linux'],
  'Healthcare Analytics Intern':['python','sql','pandas','statistics','healthcare data','data cleaning','visualization','privacy','communication','excel','machine learning','snowflake'],
  'Software Engineering Intern':['java','python','data structures','algorithms','git','testing','apis','databases','javascript','docker','cloud','object-oriented programming']
};
function normalizeSkill(s){return s.trim().toLowerCase().replace(/\s+/g,' ')}
function analyzeCareer(){const role=$('#roleSelect').value,required=roleProfiles[role],raw=$('#skillsInput').value.toLowerCase(),aliases={'data analysis':'statistics','data cleaning':'data cleaning','jupyter notebook':'jupyter','oop':'object-oriented programming','js':'javascript'};let have=raw.split(/[,;\n•]+/).map(normalizeSkill).filter(Boolean).map(s=>aliases[s]||s);const matched=required.filter(r=>have.some(h=>h.includes(r)||r.includes(h))),missing=required.filter(r=>!matched.includes(r));const score=Math.round(35+65*matched.length/required.length);$('#careerScore').textContent=score;$('#careerRing').style.setProperty('--score',score);$('#careerTitle').textContent=score>=82?`Competitive foundation for ${role}`:score>=65?`Strong foundation for ${role}`:`Promising start for ${role}`;$('#careerSummary').textContent=`You match ${matched.length} of ${required.length} modeled skill signals. Your fastest improvement path is to create visible evidence for ${missing.slice(0,3).join(', ')||'advanced project delivery'}.`;$('#matchedSkills').innerHTML=matched.map(s=>`<span>${escapeHTML(s)}</span>`).join('')||'<span>Build foundational evidence</span>';$('#missingSkills').innerHTML=missing.slice(0,7).map(s=>`<span>${escapeHTML(s)}</span>`).join('');const steps=[['THIS WEEK',missing[0]?`Learn ${missing[0]}`:'Polish portfolio evidence','Complete one focused tutorial and document the result.'],['NEXT PROJECT',missing[1]?`Prove ${missing[1]}`:'Deploy an end-to-end project','Ship a measurable feature with tests and a public demo.'],['INTERVIEW STORY','Connect skill to impact','Explain the problem, model, tradeoff, result, and next iteration.']];$('#careerRoadmap').innerHTML=steps.map(x=>`<div class="roadmap-step"><span>${x[0]}</span><b>${escapeHTML(x[1])}</b><small>${escapeHTML(x[2])}</small></div>`).join('');$('#metricCareer').textContent=score}
$('#analyzeSkills').onclick=analyzeCareer;$('#roleSelect').onchange=analyzeCareer;analyzeCareer();
const projectBullets=$('#resumeBullets').textContent;$('#copyResumeBullets').onclick=()=>copyText(projectBullets);$('#copyFinalBullets').onclick=()=>copyText(projectBullets);

// ---------- Campus navigator ----------
const buildings={
  'Lawson Computer Science Building':{x:40.4278,y:-86.9169,short:'LWSN'},'Wilmeth Active Learning Center':{x:40.4273,y:-86.9134,short:'WALC'},'Mathematical Sciences Building':{x:40.4263,y:-86.9156,short:'MATH'},'Class of 1950 Lecture Hall':{x:40.4267,y:-86.9142,short:'CL50'},'Wetherill Laboratory':{x:40.4260,y:-86.9150,short:'WTHR'},'Hicks Undergraduate Library':{x:40.4248,y:-86.9144,short:'HICKS'},'Hillenbrand Residence Hall':{x:40.4209,y:-86.9236,short:'HILL'},'Purdue Memorial Union':{x:40.4247,y:-86.9107,short:'PMU'},'Armstrong Hall of Engineering':{x:40.4293,y:-86.9149,short:'ARMS'},'Lilly Hall of Life Sciences':{x:40.4235,y:-86.9180,short:'LILY'}
};
const buildingNames=Object.keys(buildings);$('#fromBuilding').innerHTML=buildingNames.map(n=>`<option>${n}</option>`).join('');$('#toBuilding').innerHTML=buildingNames.map(n=>`<option>${n}</option>`).join('');$('#fromBuilding').value='Lawson Computer Science Building';$('#toBuilding').value='Wilmeth Active Learning Center';
function haversine(a,b){const R=3958.8,rad=x=>x*Math.PI/180,dlat=rad(b.x-a.x),dlon=rad(b.y-a.y),q=Math.sin(dlat/2)**2+Math.cos(rad(a.x))*Math.cos(rad(b.x))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
let routeState={from:$('#fromBuilding').value,to:$('#toBuilding').value,condition:'clear',minutes:15};
function calculateRoute(){routeState={from:$('#fromBuilding').value,to:$('#toBuilding').value,condition:$('#weatherCondition').value,minutes:+$('#transitionMinutes').value};const a=buildings[routeState.from],b=buildings[routeState.to],miles=haversine(a,b)*1.17,base=miles/3*60+2,mult={clear:1,rain:1.16,snow:1.38,crowded:1.22}[routeState.condition],walk=base*mult,buffer=routeState.minutes-walk,risk=buffer>=5?'Low':buffer>=1.5?'Moderate':'High';const score=clamp(Math.round(100-(walk/routeState.minutes)*28-(risk==='High'?28:risk==='Moderate'?12:0)),20,98);$('#routeResult').innerHTML=`<h4>${risk} transition risk · ${round(walk,1)} min estimated</h4><p>${round(miles,2)} miles from ${buildings[routeState.from].short} to ${buildings[routeState.to].short}. You have ${round(buffer,1)} minutes of modeled buffer under ${routeState.condition} conditions. ${risk==='High'?'Leave the prior class immediately or identify a backup route.':risk==='Moderate'?'The route is feasible, but delays could erase the buffer.':'The transition has a healthy resilience margin.'}</p>`;$('#metricRoute').textContent=score;$('#mapsLink').href=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(routeState.from+', '+currentUniversity())}&destination=${encodeURIComponent(routeState.to+', '+currentUniversity())}&travelmode=walking`;drawCampusMap()}
function drawCampusMap(){const canvas=$('#campusMap'),s=setupCanvas(canvas);if(!s)return;const {ctx,w,h}=s,c=paletteColors(),xs=buildingNames.map(n=>buildings[n].y),ys=buildingNames.map(n=>buildings[n].x),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),pad=45;ctx.clearRect(0,0,w,h);ctx.fillStyle=root.classList.contains('light')?'#eef1f7':'#0b1020';ctx.fillRect(0,0,w,h);for(let i=0;i<12;i++){ctx.strokeStyle=c.line;ctx.beginPath();ctx.moveTo(0,i*h/12);ctx.lineTo(w,i*h/12);ctx.stroke()}for(let i=0;i<16;i++){ctx.beginPath();ctx.moveTo(i*w/16,0);ctx.lineTo(i*w/16,h);ctx.stroke()}const pos=n=>({x:pad+(buildings[n].y-xmin)/(xmax-xmin)*(w-pad*2),y:h-pad-(buildings[n].x-ymin)/(ymax-ymin)*(h-pad*2)});buildingNames.forEach(n=>{const p=pos(n),active=n===routeState.from||n===routeState.to;ctx.fillStyle=active?c.gold:c.cyan;ctx.beginPath();ctx.arc(p.x,p.y,active?7:4,0,Math.PI*2);ctx.fill();ctx.fillStyle=c.text;ctx.font='10px sans-serif';ctx.fillText(buildings[n].short,p.x+8,p.y-7)});const a=pos(routeState.from),b=pos(routeState.to);ctx.strokeStyle=c.gold;ctx.lineWidth=3;ctx.setLineDash([8,7]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo((a.x+b.x)/2+25,(a.y+b.y)/2-35,b.x,b.y);ctx.stroke();ctx.setLineDash([])}
$('#calculateRoute').onclick=calculateRoute;calculateRoute();

$('#resetDemo').onclick=()=>{storage.remove('atlasiq_courses');['A','B','C'].forEach(x=>storage.remove('atlasiq_scenario_'+x));selectedCourses=starterCourseIds.map(id=>courseCatalog.find(c=>c.id===id));$('#workHours').value=8;$('#clubHours').value=5;$('#sleepHours').value=7.5;$('#commute').value=28;renderCourses();updateSemester();renderScenarios();toast('Private workspace reset')};

// ---------- AtlasIQ Studio data engine ----------
const dataState={name:'',domain:'education',rows:[],profile:null,model:null,chart:{},simulation:null};
function seeded(seed=42){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296)}
function gaussian(rng){let u=0,v=0;while(!u)u=rng();while(!v)v=rng();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function isoDate(start,i){const d=new Date(start);d.setDate(d.getDate()+i);return d.toISOString().slice(0,10)}
function sampleData(domain,n=96){const r=seeded({healthcare:11,finance:22,sports:33,climate:44,education:55}[domain]||77),rows=[];
  for(let i=0;i<n;i++){
    if(domain==='healthcare'){const age=Math.round(20+r()*65),bmi=round(18+r()*18+gaussian(r)*1.8,1),bp=Math.round(95+age*.35+bmi*.7+gaussian(r)*8),adherence=clamp(round(55+r()*45-gaussian(r)*4,1),20,100),prior=Math.max(0,Math.round(r()*4-1)),risk=clamp(round(age*.32+bmi*.7+bp*.16+prior*8-adherence*.28+gaussian(r)*5,1),2,98);rows.push({patient_id:`P${String(i+1).padStart(3,'0')}`,age,bmi,blood_pressure:bp,prior_readmissions:prior,medication_adherence:adherence,risk_score:risk,high_risk:risk>58?'Yes':'No'})}
    if(domain==='finance'){const t=i,season=Math.sin(i/8)*9,revenue=round(180+1.25*t+season+gaussian(r)*9,2),marketing=round(31+Math.sin(i/6)*5+r()*7,2),retention=round(clamp(82-Math.max(0,i-62)*.38+gaussian(r)*2.2,48,94),2),conversion=round(clamp(4.2+marketing*.035+retention*.025+gaussian(r)*.35,2,10),2),profit=round(revenue*.42-marketing*1.65+(retention-70)*.8+gaussian(r)*5,2);rows.push({date:isoDate('2026-01-01',i),region:['North','South','East','West'][i%4],revenue,marketing_spend:marketing,retention_rate:retention,conversion_rate:conversion,profit})}
    if(domain==='sports'){const mins=round(22+r()*17,1),points=round(mins*.58+gaussian(r)*5,1),assists=round(Math.max(0,mins*.15+gaussian(r)*2),1),rebounds=round(Math.max(0,mins*.2+gaussian(r)*2.5),1),eff=round(points+assists*1.5+rebounds*1.2-(r()*5),1),momentum=round(50+Math.sin(i/5)*20+gaussian(r)*8,1),win=eff+momentum*.25>38?'Win':'Loss';rows.push({game:i+1,team:['Gold','Black','White','Gray'][i%4],minutes:mins,points,assists,rebounds,efficiency:eff,momentum,game_result:win})}
    if(domain==='climate'){const season=Math.sin(i/15),temp=round(58+season*24+gaussian(r)*4,1),humidity=round(clamp(65-season*12+gaussian(r)*7,25,98),1),co2=round(418+i*.08+gaussian(r)*1.2,2),rain=round(Math.max(0,humidity*.11-temp*.035+gaussian(r)*2.2),2),heat_index=round(temp+Math.max(0,humidity-60)*.08,1);rows.push({date:isoDate('2026-01-01',i),temperature:temp,humidity,co2_ppm:co2,rainfall_mm:rain,heat_index})}
    if(domain==='education'){const attendance=round(65+r()*35,1),study=round(r()*15,1),prior=round(55+r()*42,1),assign=round(clamp(58+attendance*.34+study*1.3+gaussian(r)*8,20,100),1),stress=round(clamp(82-study*1.8-attendance*.25+gaussian(r)*9,5,100),1),finalGrade=round(clamp(prior*.35+attendance*.18+study*1.25+assign*.28-stress*.06+gaussian(r)*4,35,100),1);rows.push({student_id:`S${String(i+1).padStart(3,'0')}`,attendance_rate:attendance,study_hours:study,prior_grade:prior,assignment_completion:assign,stress_index:stress,final_grade:finalGrade,support_needed:finalGrade<70?'Yes':'No'})}
  }
  // Insert a few realistic quality issues for profiling.
  if(rows.length>20){const keys=Object.keys(rows[0]);rows[7][keys[2]]='';rows[18][keys[3]]='';if(domain!=='sports')rows[31][keys.at(-2)]=null;}
  return rows;
}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'){if(quoted&&next==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell.trim());cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell.trim());if(row.some(v=>v!==''))rows.push(row);row=[];cell=''}else cell+=ch}if(cell.length||row.length){row.push(cell.trim());rows.push(row)}if(rows.length<2)throw new Error('CSV needs a header and at least one data row.');const headers=rows[0].map((h,i)=>h||`column_${i+1}`);return rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
function toNum(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/[$,%]/g,''));return Number.isFinite(n)?n:null}
function pearson(a,b){const pairs=a.map((v,i)=>[v,b[i]]).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y));if(pairs.length<3)return 0;const ax=pairs.map(x=>x[0]),bx=pairs.map(x=>x[1]),am=avg(ax),bm=avg(bx),num=sum(pairs.map(([x,y])=>(x-am)*(y-bm))),den=Math.sqrt(sum(ax.map(x=>(x-am)**2))*sum(bx.map(x=>(x-bm)**2)));return den?num/den:0}
function quantile(sorted,q){if(!sorted.length)return 0;const pos=(sorted.length-1)*q,base=Math.floor(pos),rest=pos-base;return sorted[base+1]!==undefined?sorted[base]+rest*(sorted[base+1]-sorted[base]):sorted[base]}
function profileRows(rows){const columns=Object.keys(rows[0]||{}),profiles={};let totalMissing=0,totalOutliers=0;for(const col of columns){const raw=rows.map(r=>r[col]),missing=raw.filter(v=>v===null||v===undefined||String(v).trim()==='').length,nums=raw.map(toNum),validNums=nums.filter(Number.isFinite),numeric=validNums.length>=Math.max(3,(raw.length-missing)*.75);let p={name:col,type:numeric?'numeric':(/date|time/i.test(col)&&raw.filter(v=>!isNaN(Date.parse(v))).length>raw.length*.7?'date':'categorical'),missing,unique:new Set(raw.filter(v=>v!==''&&v!=null).map(String)).size};if(numeric){const sorted=[...validNums].sort((a,b)=>a-b),q1=quantile(sorted,.25),q3=quantile(sorted,.75),iqr=q3-q1,lo=q1-1.5*iqr,hi=q3+1.5*iqr,outliers=validNums.filter(v=>v<lo||v>hi).length;p={...p,mean:avg(validNums),min:Math.min(...validNums),max:Math.max(...validNums),median:quantile(sorted,.5),std:Math.sqrt(avg(validNums.map(v=>(v-avg(validNums))**2))),outliers,values:nums};totalOutliers+=outliers}profiles[col]=p;totalMissing+=missing}
  const numeric=columns.filter(c=>profiles[c].type==='numeric'),correlations=[];for(let i=0;i<numeric.length;i++)for(let j=i+1;j<numeric.length;j++){correlations.push({a:numeric[i],b:numeric[j],r:pearson(profiles[numeric[i]].values,profiles[numeric[j]].values)})}correlations.sort((a,b)=>Math.abs(b.r)-Math.abs(a.r));const missingPct=100*totalMissing/(Math.max(1,rows.length*columns.length)),quality=clamp(Math.round(100-missingPct*1.25-Math.min(20,totalOutliers/Math.max(1,rows.length)*12)-Math.max(0,columns.length-18)*.3),30,100);return{columns,profiles,numeric,correlations,missingPct,totalOutliers,quality,rows:rows.length}}
function domainTitle(d){return({healthcare:'Healthcare Risk Sample',finance:'Financial Performance Sample',sports:'Sports Performance Sample',climate:'Climate Trends Sample',education:'Student Outcomes Sample'})[d]||'Uploaded Dataset'}
function loadDomain(domain){dataState.domain=domain;dataState.name=domainTitle(domain);dataState.rows=sampleData(domain);setData(dataState.rows,dataState.name);$$('[data-domain]').forEach(b=>b.classList.toggle('active',b.dataset.domain===domain));toast(`${domainTitle(domain)} loaded`)}
function setData(rows,name='Uploaded Dataset'){if(!rows.length)throw new Error('No rows found.');dataState.rows=rows.slice(0,5000);dataState.name=name;dataState.profile=profileRows(dataState.rows);dataState.model=null;$('#uploadZone').classList.add('hidden');$('#dataWorkspace').classList.remove('hidden');renderProfile();populateColumnControls();activateStudio('data');}
function renderProfile(){const p=dataState.profile;$('#datasetName').textContent=dataState.name;$('#datasetMeta').textContent=`${p.rows.toLocaleString()} rows · ${p.columns.length} columns · analyzed locally`;$('#qualityScore').textContent=p.quality;$('#missingPercent').textContent=round(p.missingPct,1);$('#outlierCount').textContent=p.totalOutliers;const top=p.correlations[0];$('#topCorrelation').textContent=top?Math.abs(top.r).toFixed(2):'N/A';$('#topCorrelationLabel').textContent=top?`${top.a} ↔ ${top.b}`:'No numeric pair';const head=$('#dataPreview thead'),body=$('#dataPreview tbody'),cols=p.columns.slice(0,9);head.innerHTML='<tr>'+cols.map(c=>`<th>${escapeHTML(c)}</th>`).join('')+'</tr>';body.innerHTML=dataState.rows.slice(0,12).map(r=>'<tr>'+cols.map(c=>`<td>${escapeHTML(r[c]??'')}</td>`).join('')+'</tr>').join('');$('#columnList').innerHTML=p.columns.map(c=>{const x=p.profiles[c];return`<div class="column-item"><div><b>${escapeHTML(c)}</b><span>${x.type}</span></div><small>${x.unique} unique · ${x.missing} missing${x.type==='numeric'?` · μ ${round(x.mean,2)}`:''}</small></div>`}).join('');$('#aiSummaryText').textContent=generateSummary();renderPreprocessing();}
function generateSummary(){const p=dataState.profile,top=p.correlations[0],numeric=p.numeric;let text=`AtlasIQ profiled ${p.rows} records across ${p.columns.length} variables. Data quality is ${p.quality}/100 with ${round(p.missingPct,1)}% missing cells and ${p.totalOutliers} IQR-based outlier flags.`;if(top)text+=` The strongest numeric relationship is ${top.a} versus ${top.b} (r=${round(top.r,2)}), which is ${Math.abs(top.r)>.7?'strong':Math.abs(top.r)>.4?'moderate':'weak-to-moderate'}.`;if(dataState.domain==='finance'&&p.profiles.retention_rate)text+=` Retention averages ${round(p.profiles.retention_rate.mean,1)}%, and later records should be inspected for deterioration before treating the revenue trend as sustainable.`;if(dataState.domain==='healthcare')text+=` Risk outputs are educational estimates and must not be interpreted as diagnosis or clinical advice.`;if(dataState.domain==='education'&&p.profiles.final_grade)text+=` Final grades average ${round(p.profiles.final_grade.mean,1)}, with attendance, study time, prior performance, and assignment completion available as candidate drivers.`;if(!numeric.length)text+=' The dataset is primarily categorical, so frequency analysis and classification are more appropriate than numeric forecasting.';return text}
function populateColumnControls(){const p=dataState.profile;const all=p.columns,numeric=p.numeric;const options=arr=>arr.map(c=>`<option value="${escapeHTML(c)}">${escapeHTML(c)}</option>`).join('');$('#xColumn').innerHTML=options(all);$('#yColumn').innerHTML=options(numeric.length?numeric:all);$('#targetColumn').innerHTML=options(all);$('#simTarget').innerHTML=options(numeric);$('#simFeature').innerHTML=options(numeric);const likely={healthcare:'risk_score',finance:'profit',sports:'efficiency',climate:'rainfall_mm',education:'final_grade'}[dataState.domain];if(all.includes(likely)){['#yColumn','#targetColumn','#simTarget'].forEach(s=>$(s).value=likely)}const feature=numeric.find(c=>c!==likely);if(feature){$('#xColumn').value=feature;$('#simFeature').value=feature}dataState.chart={x:$('#xColumn').value,y:$('#yColumn').value,type:'scatter'};renderProfileChatReset()}
function renderPreprocessing(){if(!dataState.profile)return;const p=dataState.profile,items=[];for(const c of p.columns){const x=p.profiles[c];if(x.missing)items.push(`<div class="preprocess-item"><b>${escapeHTML(c)}:</b> impute or investigate ${x.missing} missing value${x.missing>1?'s':''}.</div>`);if(x.type==='numeric'&&x.outliers)items.push(`<div class="preprocess-item"><b>${escapeHTML(c)}:</b> inspect ${x.outliers} IQR outlier flag${x.outliers>1?'s':''}; preserve valid rare cases.</div>`)}if(p.numeric.length>1)items.push('<div class="preprocess-item"><b>Numeric features:</b> standardize before distance-based models such as k-NN.</div>');if(p.columns.some(c=>p.profiles[c].type==='categorical'))items.push('<div class="preprocess-item"><b>Categorical features:</b> encode carefully and avoid implying an ordinal relationship.</div>');$('#preprocessingPlan').innerHTML=items.slice(0,7).join('')||'<div class="preprocess-item"><b>Ready:</b> no obvious preprocessing blocker detected.</div>'}

// upload behavior
const uploadZone=$('#uploadZone'),csvInput=$('#csvInput');
$('#browseBtn').onclick=e=>{e.stopPropagation();csvInput.click()};uploadZone.onclick=e=>{if(e.target.closest('button'))return;csvInput.click()};uploadZone.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')csvInput.click()};['dragenter','dragover'].forEach(ev=>uploadZone.addEventListener(ev,e=>{e.preventDefault();uploadZone.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>uploadZone.addEventListener(ev,e=>{e.preventDefault();uploadZone.classList.remove('dragging')}));uploadZone.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)readCSVFile(f)});csvInput.onchange=e=>{const f=e.target.files[0];if(f)readCSVFile(f)};
function readCSVFile(file){if(file.size>8_000_000)return toast('Please use a CSV under 8 MB for this browser demo');const reader=new FileReader();reader.onload=()=>{try{const rows=parseCSV(reader.result);dataState.domain='custom';setData(rows,file.name)}catch(err){toast(err.message)}};reader.readAsText(file)}
$('#loadDemoBtn').onclick=()=>loadDomain('education');$('#replaceData').onclick=()=>{$('#dataWorkspace').classList.add('hidden');uploadZone.classList.remove('hidden');csvInput.value=''};$$('[data-domain]').forEach(b=>b.onclick=()=>loadDomain(b.dataset.domain));

// ---------- Visualizations ----------
function cleanPairs(xc,yc){return dataState.rows.map(r=>[toNum(r[xc]),toNum(r[yc])]).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y))}
function categoryAggregate(xc,yc){const map=new Map;for(const r of dataState.rows){const k=String(r[xc]??'Missing'),v=toNum(r[yc]);if(Number.isFinite(v)){const a=map.get(k)||[];a.push(v);map.set(k,a)}}return [...map.entries()].slice(0,20).map(([k,v])=>[k,avg(v)])}
function renderMainChart(){if(!dataState.profile)return;const x=$('#xColumn').value,y=$('#yColumn').value,type=$('#chartType').value,canvas=$('#mainChart');dataState.chart={x,y,type};$('#mainChartTitle').textContent=`${y} by ${x}`;const xp=dataState.profile.profiles[x],yp=dataState.profile.profiles[y];$('#timeSliderWrap').classList.toggle('hidden',xp?.type!=='date');let fraction=+$('#timeSlider').value/100,rows=dataState.rows.slice(0,Math.max(2,Math.floor(dataState.rows.length*fraction)));
  if(type==='scatter'&&xp?.type==='numeric'&&yp?.type==='numeric'){const pairs=rows.map(r=>[toNum(r[x]),toNum(r[y])]).filter(a=>a.every(Number.isFinite));drawScatter(canvas,pairs.map(a=>a[0]),pairs.map(a=>a[1]),{xLabel:x,yLabel:y})}
  else if(type==='line'){const vals=rows.map(r=>toNum(r[y])).filter(Number.isFinite);drawLineChart(canvas,vals,{labels:rows.map(r=>String(r[x]).slice(0,10)),color:'cyan'})}
  else if(type==='hist'){const vals=rows.map(r=>toNum(r[y])).filter(Number.isFinite),lo=Math.min(...vals),hi=Math.max(...vals),bins=12,width=(hi-lo||1)/bins,counts=Array(bins).fill(0);vals.forEach(v=>counts[Math.min(bins-1,Math.floor((v-lo)/width))]++);drawBarChart(canvas,counts.map((_,i)=>round(lo+i*width,1)),counts,{color:'purple'})}
  else {const ag=categoryAggregate(x,y);drawBarChart(canvas,ag.map(a=>a[0]),ag.map(a=>a[1]),{color:'gold'})}}
$('#renderChart').onclick=renderMainChart;$('#timeSlider').oninput=e=>{$('#timeSliderOut').textContent=e.target.value+'%';renderMainChart()};
function renderCorrelation(){if(!dataState.profile)return;const canvas=$('#corrCanvas'),s=setupCanvas(canvas);if(!s)return;const {ctx,w,h}=s,c=paletteColors(),cols=dataState.profile.numeric.slice(0,8),n=cols.length;ctx.clearRect(0,0,w,h);if(n<2){ctx.fillStyle=c.muted;ctx.fillText('Need at least two numeric columns.',20,40);return}const pad=90,size=Math.min((w-pad-12)/n,(h-pad-12)/n);ctx.font='9px sans-serif';cols.forEach((col,i)=>{ctx.save();ctx.translate(pad+i*size+size*.45,pad-9);ctx.rotate(-.55);ctx.fillStyle=c.muted;ctx.textAlign='right';ctx.fillText(col.slice(0,14),0,0);ctx.restore();ctx.textAlign='right';ctx.fillText(col.slice(0,13),pad-8,pad+i*size+size*.6)});for(let i=0;i<n;i++)for(let j=0;j<n;j++){const r=i===j?1:pearson(dataState.profile.profiles[cols[i]].values,dataState.profile.profiles[cols[j]].values),alpha=.15+Math.abs(r)*.75;ctx.fillStyle=r>=0?`rgba(102,229,255,${alpha})`:`rgba(255,125,141,${alpha})`;ctx.fillRect(pad+j*size,pad+i*size,size-2,size-2);ctx.fillStyle=Math.abs(r)>.55?'#071019':c.text;ctx.textAlign='center';ctx.fillText(r.toFixed(2),pad+j*size+size/2,pad+i*size+size*.6)}}
$('#downloadChart').onclick=()=>{const a=document.createElement('a');a.download='atlasiq-visualization.png';a.href=$('#mainChart').toDataURL('image/png');a.click()};

// ---------- Lightweight AutoML ----------
function buildDataset(target){const p=dataState.profile,tp=p.profiles[target],featureNames=p.numeric.filter(c=>c!==target),numericTarget=tp.type==='numeric';if(!featureNames.length)throw new Error('At least one numeric feature is required.');const rows=[];for(const r of dataState.rows){const y=numericTarget?toNum(r[target]):String(r[target]??'').trim();if((numericTarget&&!Number.isFinite(y))||(!numericTarget&&!y))continue;rows.push({x:featureNames.map(f=>toNum(r[f])),y})}const means=featureNames.map((_,j)=>avg(rows.map(o=>o.x[j]).filter(Number.isFinite)));rows.forEach(o=>o.x=o.x.map((v,j)=>Number.isFinite(v)?v:means[j]));const train=rows.filter((_,i)=>i%5!==0),test=rows.filter((_,i)=>i%5===0);return{train,test,featureNames,numericTarget}}
function standardizer(rows){const d=rows[0].x.length,means=Array(d).fill(0).map((_,j)=>avg(rows.map(r=>r.x[j]))),stds=Array(d).fill(0).map((_,j)=>Math.sqrt(avg(rows.map(r=>(r.x[j]-means[j])**2)))||1);return{x:x=>x.map((v,j)=>(v-means[j])/stds[j]),means,stds}}
function r2Score(y,p){const m=avg(y),ss=sum(y.map(v=>(v-m)**2));return ss?1-sum(y.map((v,i)=>(v-p[i])**2))/ss:0}
function accuracy(y,p){return avg(y.map((v,i)=>v===p[i]?1:0))}
function trainLinear(train,lambda1=0,lambda2=0){const st=standardizer(train),X=train.map(r=>[1,...st.x(r.x)]),y=train.map(r=>r.y),d=X[0].length,w=Array(d).fill(0),lr=.028;for(let it=0;it<1400;it++){const g=Array(d).fill(0);for(let i=0;i<X.length;i++){const err=sum(X[i].map((v,j)=>v*w[j]))-y[i];for(let j=0;j<d;j++)g[j]+=err*X[i][j]}for(let j=0;j<d;j++){g[j]/=X.length;if(j){g[j]+=lambda2*w[j]+lambda1*Math.sign(w[j])}w[j]-=lr*g[j]}}return{x:(x)=>sum([1,...st.x(x)].map((v,j)=>v*w[j])),weights:w.slice(1).map((v,j)=>v/st.stds[j])}}
function distance(a,b){return Math.sqrt(sum(a.map((v,i)=>(v-b[i])**2)))}
function knnPredict(train,x,k=5,numeric=true){const st=standardizer(train),tx=st.x(x),sorted=train.map(r=>({d:distance(st.x(r.x),tx),y:r.y})).sort((a,b)=>a.d-b.d).slice(0,k);if(numeric)return avg(sorted.map(o=>o.y));const counts={};sorted.forEach(o=>counts[o.y]=(counts[o.y]||0)+1);return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0]}
function regressionStump(train){let best={err:Infinity,j:0,t:0,left:0,right:0};for(let j=0;j<train[0].x.length;j++){const vals=train.map(r=>r.x[j]).sort((a,b)=>a-b);for(let q=1;q<8;q++){const t=quantile(vals,q/8),l=train.filter(r=>r.x[j]<=t),rr=train.filter(r=>r.x[j]>t);if(!l.length||!rr.length)continue;const lm=avg(l.map(r=>r.y)),rm=avg(rr.map(r=>r.y)),err=sum(l.map(r=>(r.y-lm)**2))+sum(rr.map(r=>(r.y-rm)**2));if(err<best.err)best={err,j,t,left:lm,right:rm}}}return{x:(x)=>x[best.j]<=best.t?best.left:best.right,feature:best.j}}
function classStump(train){let best={acc:-1,j:0,t:0,left:'',right:''};const mode=a=>Object.entries(a.reduce((o,v)=>(o[v]=(o[v]||0)+1,o),{})).sort((a,b)=>b[1]-a[1])[0]?.[0];for(let j=0;j<train[0].x.length;j++){const vals=train.map(r=>r.x[j]).sort((a,b)=>a-b);for(let q=1;q<8;q++){const t=quantile(vals,q/8),l=train.filter(r=>r.x[j]<=t),rr=train.filter(r=>r.x[j]>t);if(!l.length||!rr.length)continue;const lm=mode(l.map(r=>r.y)),rm=mode(rr.map(r=>r.y)),acc=accuracy(train.map(r=>r.y),train.map(r=>r.x[j]<=t?lm:rm));if(acc>best.acc)best={acc,j,t,left:lm,right:rm}}}return{x:(x)=>x[best.j]<=best.t?best.left:best.right,feature:best.j}}
function gaussianNB(train){const classes=[...new Set(train.map(r=>r.y))],d=train[0].x.length,stats={};classes.forEach(k=>{const rows=train.filter(r=>r.y===k);stats[k]={prior:rows.length/train.length,mean:Array(d).fill(0).map((_,j)=>avg(rows.map(r=>r.x[j]))),variance:Array(d).fill(0).map((_,j)=>avg(rows.map(r=>(r.x[j]-avg(rows.map(q=>q.x[j])))**2))+.0001)}});return x=>classes.map(k=>{const s=stats[k];let log=Math.log(s.prior);for(let j=0;j<d;j++)log+=-.5*Math.log(2*Math.PI*s.variance[j])-((x[j]-s.mean[j])**2)/(2*s.variance[j]);return[k,log]}).sort((a,b)=>b[1]-a[1])[0][0]}
function featureInfluence(ds,target){const t=dataState.profile.profiles[target];if(ds.numericTarget)return ds.featureNames.map(f=>[f,Math.abs(pearson(dataState.profile.profiles[f].values,t.values))]).sort((a,b)=>b[1]-a[1]);const classes=[...new Set(dataState.rows.map(r=>String(r[target]??'')).filter(Boolean))];return ds.featureNames.map(f=>{const vals=classes.map(k=>avg(dataState.rows.filter(r=>String(r[target])===k).map(r=>toNum(r[f])).filter(Number.isFinite))),overall=avg(dataState.rows.map(r=>toNum(r[f])).filter(Number.isFinite)),v=avg(vals.map(x=>(x-overall)**2));return[f,v]}).sort((a,b)=>b[1]-a[1]).map((x,_,a)=>[x[0],x[1]/(a[0]?.[1]||1)])}
function runAutoML(){if(!dataState.profile)return toast('Load a dataset first');const target=$('#targetColumn').value;try{const ds=buildDataset(target);if(ds.train.length<10||ds.test.length<3)throw new Error('Not enough complete rows for a holdout experiment.');let models=[];if(ds.numericTarget){const mean=avg(ds.train.map(r=>r.y)),lin=trainLinear(ds.train),elastic=trainLinear(ds.train,.002,.015),stump=regressionStump(ds.train);models=[['Mean Baseline',()=>mean],['Linear Regression',lin.x],['Elastic Net Approx.',elastic.x],['k-NN Regression',x=>knnPredict(ds.train,x,Math.min(7,ds.train.length),true)],['Decision Stump',stump.x]].map(([name,fn])=>{const pred=ds.test.map(r=>fn(r.x)),score=r2Score(ds.test.map(r=>r.y),pred);return{name,score,pred}})}else{const counts={};ds.train.forEach(r=>counts[r.y]=(counts[r.y]||0)+1);const majority=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0],nb=gaussianNB(ds.train),stump=classStump(ds.train);models=[['Majority Baseline',()=>majority],['k-NN Classifier',x=>knnPredict(ds.train,x,Math.min(7,ds.train.length),false)],['Gaussian Naive Bayes',nb],['Decision Stump',stump.x]].map(([name,fn])=>{const pred=ds.test.map(r=>fn(r.x)),score=accuracy(ds.test.map(r=>r.y),pred);return{name,score,pred}})}models.sort((a,b)=>b.score-a.score);const influence=featureInfluence(ds,target);dataState.model={target,ds,models,influence};renderModelResults()}catch(e){toast(e.message)}}
function renderModelResults(){const m=dataState.model,w=m.models[0],metric=m.ds.numericTarget?'R²':'accuracy';$('#modelEmpty').classList.add('hidden');$('#modelResults').classList.remove('hidden');$('#winningModel').textContent=w.name;$('#winningScore').textContent=(w.score*100).toFixed(1)+'%';$('#winningMetric').textContent=metric;$('#winningExplanation').textContent=`Selected from ${m.models.length} local models using a deterministic holdout set. ${w.name} produced the strongest ${metric} on unseen rows.`;$('#modelGrid').innerHTML=m.models.map((x,i)=>`<article class="model-card ${i===0?'winner':''}"><span>${i===0?'BEST HOLDOUT RESULT':'CANDIDATE'}</span><b>${escapeHTML(x.name)}</b><strong>${(x.score*100).toFixed(1)}%</strong><small>${metric}</small></article>`).join('');const max=m.influence[0]?.[1]||1;$('#featureImportance').innerHTML=m.influence.slice(0,7).map(([n,v])=>`<div class="factor-row"><span>${escapeHTML(n)}</span><i><b style="--value:${clamp(v/max*100,2,100)}%"></b></i><em>${Math.round(v/max*100)}</em></div>`).join('');const top=m.influence[0];$('#modelWhy').textContent=`${w.name} won because it generalized best on the reserved 20% holdout set. ${top?`${top[0]} is the strongest measured driver under the current influence method. `:''}A production version should add cross-validation, leakage checks, fairness analysis, and domain review before deployment.`}
$('#runAutoML').onclick=runAutoML;
const methodModal=$('#methodModal');function closeMethodModal(){methodModal.classList.remove('open');methodModal.setAttribute('aria-hidden','true')}$('#showModelDetails').onclick=()=>{methodModal.classList.add('open');methodModal.setAttribute('aria-hidden','false')};methodModal.querySelector('.modal-backdrop').onclick=closeMethodModal;methodModal.querySelector('.modal-close').onclick=closeMethodModal;

// ---------- Dataset decision simulator ----------
$('#simAdjustment').oninput=e=>$('#simAdjustmentOut').textContent=(+e.target.value>0?'+':'')+e.target.value+'%';
function runDataSimulation(){if(!dataState.profile)return toast('Load a dataset first');const target=$('#simTarget').value,feature=$('#simFeature').value;if(target===feature)return toast('Choose different driver and outcome columns');const pairs=cleanPairs(feature,target);if(pairs.length<5)return toast('Not enough complete numeric pairs');const xs=pairs.map(a=>a[0]),ys=pairs.map(a=>a[1]),xm=avg(xs),ym=avg(ys),cov=avg(xs.map((x,i)=>(x-xm)*(ys[i]-ym))),variance=avg(xs.map(x=>(x-xm)**2)),slope=variance?cov/variance:0,adj=+$('#simAdjustment').value/100,newX=xm*(1+adj),pred=ym+slope*(newX-xm),r=pearson(xs,ys);dataState.simulation={target,feature,xm,ym,pred,adj,r,slope};$('#baselineOutcome').textContent=formatNumber(ym);$('#simulatedOutcome').textContent=formatNumber(pred);$('#simulationNarrative').innerHTML=`<span class="alert-dot"></span><p>A <b>${adj>=0?'+':''}${round(adj*100,0)}%</b> change in <b>${escapeHTML(feature)}</b> moves the locally estimated average <b>${escapeHTML(target)}</b> from ${formatNumber(ym)} to ${formatNumber(pred)}. The linear relationship is r=${round(r,2)}. This is a sensitivity estimate, not causal proof.</p>`;drawSimulationChart()}
function drawSimulationChart(){const c=$('#simulationChart');if(!dataState.simulation){const s=setupCanvas(c);if(s){s.ctx.clearRect(0,0,s.w,s.h);s.ctx.fillStyle=paletteColors().muted;s.ctx.fillText('Run a simulation to visualize the counterfactual.',25,40)}return}const q=dataState.simulation,vals=Array.from({length:21},(_,i)=>{const pct=-.5+i*.05;return q.ym+q.slope*(q.xm*(1+pct)-q.xm)});drawLineChart(c,vals,{labels:vals.map((_,i)=>(-50+i*5)+'%'),color:'purple',highlight:Math.round((q.adj+.5)/.05)})}
$('#runDataSimulation').onclick=runDataSimulation;

// ---------- Local conversational analyst ----------
function renderProfileChatReset(){$('#chatMessages').innerHTML='<div class="message ai">Dataset loaded. Ask me about quality, missing values, outliers, correlations, trends, modeling, or preprocessing.</div>'}
function analystAnswer(q){if(!dataState.profile)return'Load a dataset first so I have evidence to analyze.';const s=q.toLowerCase(),p=dataState.profile,top=p.correlations[0];if(/stand out|summary|overview/.test(s))return generateSummary();if(/missing/.test(s)){const cols=p.columns.filter(c=>p.profiles[c].missing).sort((a,b)=>p.profiles[b].missing-p.profiles[a].missing);return cols.length?`Missing values appear in ${cols.map(c=>`${c} (${p.profiles[c].missing})`).join(', ')}. Investigate whether the gaps are random before imputing.`:'No missing values were detected.'}if(/outlier|unusual|anomal/.test(s)){const cols=p.numeric.filter(c=>p.profiles[c].outliers).sort((a,b)=>p.profiles[b].outliers-p.profiles[a].outliers);return cols.length?`IQR screening flagged ${p.totalOutliers} potential outliers. The most affected columns are ${cols.slice(0,4).map(c=>`${c} (${p.profiles[c].outliers})`).join(', ')}. Validate them rather than deleting automatically.`:'IQR screening did not flag numeric outliers.'}if(/correl|relationship|matter|important|driver/.test(s))return top?`The strongest measured numeric relationship is ${top.a} and ${top.b}, with r=${round(top.r,2)}. Correlation does not establish causation, so test alternative explanations and possible leakage.`:'There are not enough numeric columns for correlation analysis.';if(/preprocess|clean/.test(s))return`Recommended plan: handle ${round(p.missingPct,1)}% missing cells using domain-aware imputation, inspect ${p.totalOutliers} outlier flags, standardize numeric features for distance-based models, encode categorical features, and separate preprocessing fit between train and test data.`;if(/model|automl|predict/.test(s)){if(dataState.model)return`${dataState.model.models[0].name} currently leads with ${(dataState.model.models[0].score*100).toFixed(1)}% ${dataState.model.ds.numericTarget?'R²':'accuracy'}. Treat this as an educational holdout result and add cross-validation before making a production claim.`;return'Open AutoML, choose a target, and run the model arena. I will then explain the winner and its strongest feature signals.'}if(/trend|over time|increase|decrease/.test(s)){const date=p.columns.find(c=>p.profiles[c].type==='date'),num=p.numeric[0];if(date&&num){const vals=dataState.rows.map(r=>toNum(r[num])).filter(Number.isFinite),half=Math.floor(vals.length/2),change=(avg(vals.slice(half))-avg(vals.slice(0,half)))/(Math.abs(avg(vals.slice(0,half)))||1)*100;return`${num} changes by approximately ${round(change,1)}% between the first and second halves of the dataset. Use the Visuals time window to inspect whether the shift is gradual or concentrated.`}return'No date-like column was detected. Choose a meaningful order column in Visuals to inspect progression.'}return`I can answer this dataset reliably when the question references quality, missing values, outliers, relationships, trends, preprocessing, or the current model. Try “What stands out?” or “Which variables matter most?”`}
function addChat(role,text){const div=document.createElement('div');div.className='message '+role;div.textContent=text;$('#chatMessages').appendChild(div);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight}
$('#chatForm').onsubmit=e=>{e.preventDefault();const q=$('#chatInput').value.trim();if(!q)return;addChat('user',q);$('#chatInput').value='';setTimeout(()=>addChat('ai',analystAnswer(q)),180)};$$('.suggestion-chips button').forEach(b=>b.onclick=()=>{addChat('user',b.textContent);setTimeout(()=>addChat('ai',analystAnswer(b.textContent)),160)});
$('#speakSummary').onclick=()=>{if(!('speechSynthesis'in window))return toast('Speech is not supported in this browser');speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance($('#aiSummaryText').textContent))};

$('#exportReport').onclick=()=>{if(!dataState.profile)return toast('Load a dataset first');const report={product:'AtlasIQ Studio',generated_at:new Date().toISOString(),dataset:dataState.name,domain:dataState.domain,profile:{rows:dataState.profile.rows,columns:dataState.profile.columns,quality:dataState.profile.quality,missing_percent:round(dataState.profile.missingPct,2),outlier_flags:dataState.profile.totalOutliers,strongest_correlations:dataState.profile.correlations.slice(0,10)},model:dataState.model?{target:dataState.model.target,winner:dataState.model.models[0].name,score:dataState.model.models[0].score,feature_influence:dataState.model.influence}:null,simulation:dataState.simulation,summary:generateSummary(),disclaimer:'Educational browser-native analysis. Validate results before real-world decisions.'};downloadFile('atlasiq-analysis-report.json',JSON.stringify(report,null,2))};

// ---------- ProofGraph ----------
const proofNodes=[
  {id:'Niveditha',type:'root',x:.5,y:.5,evidence:['Purdue University B.S. Data Science candidate, May 2029']},
  {id:'Python',type:'skill',x:.25,y:.23,evidence:['Technical skills: Python, Pandas, Jupyter, data cleaning','AtlasIQ local analytics engine and data profiling']},
  {id:'Statistics',type:'skill',x:.70,y:.20,evidence:['AP Statistics project using 80+ survey responses','Chi-squared test and hypothesis interpretation','AtlasIQ correlations, outliers, model evaluation']},
  {id:'Java',type:'skill',x:.83,y:.50,evidence:['Java four-player word guessing game','Object-oriented programming with collections, scoring, and GUI tracking']},
  {id:'Product Design',type:'skill',x:.73,y:.78,evidence:['AtlasIQ end-to-end product strategy and responsive interface','Impaqx product testing and improvement feedback']},
  {id:'Communication',type:'skill',x:.27,y:.80,evidence:['Taught 40+ Kumon students','100+ volunteer teaching hours with adult and Ukrainian learners']},
  {id:'Leadership',type:'skill',x:.10,y:.52,evidence:['216+ service hours as Youth Lead Volunteer','Coordinated annual donation of 1,000+ lbs of food','Presidential Volunteer Service Award — Silver']},
  {id:'AtlasIQ',type:'project',x:.50,y:.08,evidence:['Decision intelligence platform','Campus digital twin + universal data laboratory','Explainability, AutoML, simulation, and ProofGraph']},
  {id:'Data Cleaning',type:'skill',x:.93,y:.27,evidence:['Resume-listed skill','Automated missing-value and outlier profiling in AtlasIQ']},
  {id:'Teaching',type:'experience',x:.08,y:.77,evidence:['Kumon Teaching Assistant','ENGin and Montgomery Tutoring English volunteer']}
];
const proofEdges=[['Niveditha','Python'],['Niveditha','Statistics'],['Niveditha','Java'],['Niveditha','Product Design'],['Niveditha','Communication'],['Niveditha','Leadership'],['Niveditha','AtlasIQ'],['Python','AtlasIQ'],['Statistics','AtlasIQ'],['Product Design','AtlasIQ'],['Python','Data Cleaning'],['Communication','Teaching'],['Leadership','Teaching'],['Data Cleaning','AtlasIQ']];
let selectedProof='AtlasIQ';
function drawProofGraph(){const canvas=$('#proofCanvas'),s=setupCanvas(canvas);if(!s)return;const {ctx,w,h}=s,c=paletteColors(),pos={};ctx.clearRect(0,0,w,h);proofNodes.forEach(n=>pos[n.id]={x:n.x*w,y:n.y*h});proofEdges.forEach(([a,b])=>{ctx.strokeStyle='rgba(245,207,98,.18)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(pos[a].x,pos[a].y);ctx.lineTo(pos[b].x,pos[b].y);ctx.stroke()});proofNodes.forEach(n=>{const p=pos[n.id],sel=n.id===selectedProof,r=n.type==='root'?42:n.type==='project'?35:27;ctx.fillStyle=sel?c.gold:n.type==='project'?c.purple:n.type==='experience'?c.green:c.panel;ctx.strokeStyle=sel?'#fff4c0':n.type==='skill'?c.cyan:c.gold;ctx.lineWidth=sel?3:1.5;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=sel||n.type==='project'?'#111520':c.text;ctx.textAlign='center';ctx.font=`${sel?'700':'600'} ${n.id.length>12?'9':'11'}px sans-serif`;const words=n.id.split(' ');if(words.length>1){ctx.fillText(words[0],p.x,p.y-2);ctx.fillText(words.slice(1).join(' '),p.x,p.y+11)}else ctx.fillText(n.id,p.x,p.y+4)});canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*(canvas.width/(devicePixelRatio||1))/r.width,y=(e.clientY-r.top)*(canvas.height/(devicePixelRatio||1))/r.height;const hit=proofNodes.find(n=>Math.hypot(x-n.x*r.width,y-n.y*(canvas.height/(devicePixelRatio||1)))<44);if(hit){selectedProof=hit.id;renderProofEvidence();drawProofGraph()}}}
function renderProofEvidence(){const n=proofNodes.find(x=>x.id===selectedProof);$('#proofDescription').textContent=`${n.id} is backed by ${n.evidence.length} concrete evidence signal${n.evidence.length>1?'s':''}.`;$('#proofEvidence').innerHTML=n.evidence.map((e,i)=>`<div class="evidence-card"><span>EVIDENCE ${String(i+1).padStart(2,'0')}</span><b>${escapeHTML(e)}</b><small>${n.type==='skill'?'Skill proof':'Experience artifact'}</small></div>`).join('')}
$('#exportProof').onclick=()=>downloadFile('niveditha-proofgraph.json',JSON.stringify({founder:'Niveditha Mallojhala',nodes:proofNodes,edges:proofEdges},null,2));renderProofEvidence();setTimeout(drawProofGraph,80);

// ---------- About, exports, startup ----------
const aboutBio=`I'm Niveditha Mallojhala, a Data Science student at Purdue University interested in the full path from raw information to a decision someone can confidently act on. I combine statistics, programming, data cleaning, visualization, communication, and product design to build understandable, evidence-driven tools. AtlasIQ is a privacy-first decision intelligence platform that models student choices and turns raw datasets into explainable analysis.`;
$('#copyAbout').onclick=()=>copyText(aboutBio);

// initialize a useful demo while preserving the upload-first experience
setTimeout(()=>{drawAllCanvases();},100);
addEventListener('resize',()=>{clearTimeout(window.__atlasResize);window.__atlasResize=setTimeout(drawAllCanvases,100)});

// Offline registration (works after deployment over HTTPS/GitHub Pages)
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
